### ISSUE TITLE
Arrow changes

### ISSUE THREAD

**Issue by probablykasper** [TeamSpectral/Advanced-Weapons#7]
You can now add status effects to arrows. Potions can be poured into cauldrons. Then, you have to right-click the cauldron to get some potion effects to the tip of it. Once the arrow is shot, the creature it hits will recieve that effect, but 10x shorter. If you wait 10 seconds, you can dip the arrow in the liquid again, to get the effect stronger; 6x shorter lasting. 10 seconds later, you can do it again, and the effect lasts 3x shorter. You can alternatively add other effects to it, instead of making one stronger.

**Comment by kasper9n** [comment]
Closing because this recently got added to Minecraft.
